\input texinfo

@titlepage
@title BrickGame
@subtitle for version 1.0
@author mucklane
@end titlepage

@node Tetris installation
@chapter Tetris installation

@pindex sample
@cindex invoking @command{sample}

@enumerate
@item
To install, type:
@itemize
@item
    sudo make install
@end itemize

@item
To uninstall, type:
@itemize
@item
    sudo make uninstall
@end itemize

@end enumerate

@bye
